### ISSUE TITLE
sk.yml - translations missing

### ISSUE THREAD

**Issue by dan-nl** [europeana/Europeana1914-1918#3]
this [commit][1], deleted all of the translations. please update the file as soon as possible.

one item to note in regards to an empty yml file, it crashes the application because it expects a hash to be present. you can create an empty hash with something like the following if necessary:

```yaml
# Messages for Slovak (slovenčina)
# Exported from translatewiki.net
# Export driver: phpyaml
# Author: Kusavica
---
sk:
````

[1]: https://github.com/europeana/Europeana1914-1918/commit/06dbb194c21ffe92aff3d28edb2411ac385d16dd#diff-17d67cf15fed9113d9d2f435d07b8f34

**Comment by siebrand** [comment]
Initial source file was corrupt. We've fixed it. Issue can be observed at https://translatewiki.net/w/i.php?title=Europeana:Formtastic.update/sk&action=edit&undoafter=5510868&undo=5967475

**Comment by dan-nl** [comment]
firxed by https://github.com/europeana/Europeana1914-1918/blob/a88a6f3e487b39832d313d0f5ba0c342db364ff5/config/locales/sk.yml
